#!/bin/bash

############################################################################################
#                                                                                          #
# iperftester_setup : Configurar tarjetas de red y servidor local                          #
#                                                                                          #
#------------------------------------------------------------------------------------------#
#                                                                                          #
# Autor         : Felipe Muñoz Brieva - fmbrieva@gmail.com                                 #
#                                                                                          #
#------------------------------------------------------------------------------------------#
#                                                                                          #
# Modificaciones:                                                                          #
#                                                                                          #
# 03/02/2018     Versión inicial                                                           #
#   Felipe                                                                                 #
#                                                                                          #
############################################################################################

## 
. iperftester_lib

actualizarParametros

mensajeInicialIperf

#clear

leerConfigurarHost

reiniciarServidoresIperf

eval $RUTA_IPERFTESTER/iperftester_menu; 


