#!/bin/bash

############################################################################################
#                                                                                          #
# iperftester   : Realizar test iperf con servidores remotos                               #
#                                                                                          #
#------------------------------------------------------------------------------------------#
#                                                                                          #
# Versión       : 01r00                                                                    #
# Fecha         : 3/febrero/2018                                                           #
# Autor         : Felipe Muñoz Brieva - fmbrieva@gmail.com                                 #
#                                                                                          #
#------------------------------------------------------------------------------------------#
#                                                                                          #
# Modificaciones:                                                                          #
#                                                                                          #
# --01r00--       Version inicial                                                          #
# 03/02/2018                                                                               #
#   Felipe                                                                                 #
#                                                                                          #
############################################################################################

## Revisar ruta - OJO

. /opt/iperftester/iperftester_lib

mensajeInicialRoot

leerConfigurarHost

mensajeFinalRoot
