#!/bin/bash

############################################################################################
#                                                                                          #
# iperftester   : Realizar test iperf con servidores remotos                               #
#                                                                                          #
#------------------------------------------------------------------------------------------#
#                                                                                          #
# Autor         : Felipe Muñoz Brieva - fmbrieva@gmail.com                                 #
#                                                                                          #
#------------------------------------------------------------------------------------------#
#                                                                                          #
# Modificaciones:                                                                          #
#                                                                                          #
# 03/02/2018      Versión inicial                                                          #
#   Felipe                                                                                 #
#                                                                                          #
############################################################################################

. /opt/iperftester/iperftester_lib

mensajeInicialRoot

leerConfigurarHost

mensajeFinalRoot
